version: '3.9'
services:
  frontend:
    build:
      context: ./node
      args:
        NODE_VERSION: ${NODE_VERSION}
    volumes:
      - ./src/frontend/jasontech-erp:/app
    container_name: jasontech-erp-frontend
    ports:
      - "${NODE_PORT}:3000"
    restart: always

  app:
    build:
      context: ./go_app
      args:
        GO_VERSION: ${GO_VERSION}
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      - ./src/backend:/app
    container_name: jasontech-erp-app
    ports:
      - "${GO_PORT}:8000"
    depends_on:
      - db
    restart: always

  db:
    image: postgres:${DB_VERSION}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    container_name: ${DB_HOST}
    restart: always

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: ./db_data
      o: bind
